

public with sharing class InitParam {

    public String configGlossary_installationAt;
    public String configGlossary_adminEmail;
    public String configGlossary_poweredBy;
    public String configGlossary_poweredByIcon;
    public String configGlossary_staticPath;
    public String templateProcessorClass;
    public String templateLoaderClass;
    public String templatePath;
    public String templateOverridePath;
    public String defaultListTemplate;
    public String defaultFileTemplate;
    public Boolean useJSP;
    public String jspListTemplate;
    public String jspFileTemplate;
    public Integer cachePackageTagsTrack;
    public Integer cachePackageTagsStore;
    public Integer cachePackageTagsRefresh;
    public Integer cacheTemplatesTrack;
    public Integer cacheTemplatesStore;
    public Integer cacheTemplatesRefresh;
    public Integer cachePagesTrack;
    public Integer cachePagesStore;
    public Integer cachePagesRefresh;
    public Integer cachePagesDirtyRead;
    public String searchEngineListTemplate;
    public String searchEngineFileTemplate;
    public String searchEngineRobotsDb;
    public Boolean useDataStore;
    public String dataStoreClass;
    public String redirectionClass;
    public String dataStoreName;
    public String dataStoreDriver;
    public String dataStoreUrl;
    public String dataStoreUser;
    public String dataStorePassword;
    public String dataStoreTestQuery;
    public String dataStoreLogFile;
    public Integer dataStoreInitConns;
    public Integer dataStoreMaxConns;
    public Integer dataStoreConnUsageLimit;
    public String dataStoreLogLevel;
    public Integer maxUrlLength;
    public String mailHost;
    public String mailHostOverride;
    public Integer log;
    public String logLocation;
    public String logMaxSize;
    public Integer dataLog;
    public String dataLogLocation;
    public String dataLogMaxSize;
    public String removePageCache;
    public String removeTemplateCache;
    public String fileTransferFolder;
    public Integer lookInContext;
    public Integer adminGroupID;
    public Boolean betaServer;


}